config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end
  
  root 'pics#index'
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pics
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [ :show, :edit, :update, :destroy, :upvote ]
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @pics = Pic.all.order('created_at DESC')
  end
  
  def show
    
  end
  
  def new
    @pic = current_user.pics.build
  end
  
  def create
    @pic = current_user.pics.build(pic_params)
    
    if @pic.save
      redirect_to @pic, notice: "Yes! pic posted!"
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats pic was updated"
    else
      render 'edit'
    end
  end
  
  def destroy
    @pic.destroy
    redirect_to root_path
  end
  
  def upvote
    @pic.upvote_by current_user
    redirect_to :back
  end
  
  private
    def pic_params
      params.require(:pic).permit(:title, :description, :image)
    end
    
    def find_pic
      @pic = Pic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pedstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="nav navbar navbar-static-top navbar-inverse">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Pedstagram", root_path %>
      </div>
      <div class="nav navbar navbar-right secondary-nav">
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li><%= link_to "GramIT", new_pic_path, class: "btn btn-info gramit-btn" %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Join", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
  
  <div class="container">
    <%= render partial: "layouts/flash_message", flash: flash %>
      <%= yield %>
  </div>
</body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: { multipart: true } do |f| %>
  <% if @pic.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@pic.errors.count, "error") %> prevented this Pic from saving</h2>
        <ul>
          <% @pic.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>
  
  <div class="form-group"><%= f.input :image, input_html: { class: 'form-control'} %></div>
  <div class="form-group"><%= f.input :title, input_html: { class: 'form-control'} %></div>
  <div class="form-group"><%= f.input :description, input_html: { class: 'form-control'} %></div>
  <%= f.button :submit, class: 'btn btn-default' %>
<% end %>

app/views/pics/edit.html.erb
<div class="edit_page col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Fix pic!</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">
            Right now
            <%= image_tag @pic.image.url(:thumb) %>
          </strong>
        </div>
        <%= render 'form' %>
        <%= link_to "Cancel", pic_path %>
      </div>
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-8 col-md-offset-4">
  <div class="transitions-enabled" id="pics">
      <% @pics.each do |pic| %>
        <div class="box panel panel-default">
          <%= link_to (image_tag pic.image.url), pic %>
          <h2><%= link_to pic.title, pic %></h2>
        </div>
      <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post Pic</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
        <%= link_to 'Back', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/pics/show.html.erb
<div id="pic_show" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel heading pic_image">
        <%= image_tag @pic.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1><%= @pic.title %></h1>
        <p><%= simple_format(@pic.description) %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p>Uploaded by: <%= @pic.user.email %></p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-thumbs-up"> </span>
                <strong><%= @pic.get_upvotes.size %></strong>
              <% end %>
              <% if current_user %>
                <%= link_to "Back", root_path, class: "btn btn-primary" %>
                <%= link_to "Edit", edit_pic_path, class: "btn btn-info" %>
                <%= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>